module Layout exposing (qwerty)


qwerty : List (List ( String, String ))
qwerty =
    -- ("view", "code")
    [ [ ( "`", "Backquote" )
      , ( "1", "Digit1" )
      , ( "2", "Digit2" )
      , ( "3", "Digit3" )
      , ( "4", "Digit4" )
      , ( "5", "Digit5" )
      , ( "6", "Digit6" )
      , ( "7", "Digit7" )
      , ( "8", "Digit8" )
      , ( "9", "Digit9" )
      , ( "0", "Digit0" )
      , ( "-", "Minus" )
      , ( "=", "Equal" )
      , ( "⌫", "Backspace" )
      ]
    , [ ( "⇥", "Tab" )
      , ( "Q", "KeyQ" )
      , ( "W", "KeyW" )
      , ( "E", "KeyE" )
      , ( "R", "KeyR" )
      , ( "T", "KeyT" )
      , ( "Y", "KeyY" )
      , ( "U", "KeyU" )
      , ( "I", "KeyI" )
      , ( "O", "KeyO" )
      , ( "P", "KeyP" )
      , ( "[", "BracketLeft" )
      , ( "]", "BracketRight" )
      , ( "\\", "Backslash" )
      ]
    , [ ( "⇪ Caps", "CapsLock" )
      , ( "A", "KeyA" )
      , ( "S", "KeyS" )
      , ( "D", "KeyD" )
      , ( "F", "KeyF" )
      , ( "G", "KeyG" )
      , ( "H", "KeyH" )
      , ( "J", "KeyJ" )
      , ( "K", "KeyK" )
      , ( "L", "KeyL" )
      , ( ";", "Semicolon" )
      , ( "'", "Quote" )
      , ( "⏎", "Enter" )
      ]
    , [ ( "SHIFT", "ShiftLeft" )
      , ( "Z", "KeyZ" )
      , ( "X", "KeyX" )
      , ( "C", "KeyC" )
      , ( "V", "KeyV" )
      , ( "B", "KeyB" )
      , ( "N", "KeyN" )
      , ( "M", "KeyM" )
      , ( ",", "Comma" )
      , ( ".", "Period" )
      , ( "/", "Slash" )
      , ( "SHIFT", "ShiftRight" )
      ]
    , [ ( "CTRL", "ControlLeft" ), ( "ALT", "AltLeft" ), ( " ", "Space" ), ( "ALT", "AltRight" ), ( "CTRL", "ControlRight" ) ]
    ]
